forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
libgdma.so         00001486A4AF510F  for__signal_handl     Unknown  Unknown
libpthread-2.28.s  00001486B8781B20  Unknown               Unknown  Unknown
core.cpython-39-x  00001486A83B5DF5  Unknown               Unknown  Unknown
core.cpython-39-x  00001486A8B18C8F  Unknown               Unknown  Unknown
core.cpython-39-x  00001486A7B36E56  Unknown               Unknown  Unknown
core.cpython-39-x  00001486A8F00341  Unknown               Unknown  Unknown
core.cpython-39-x  00001486A8EFF17C  _ZN3psi11MintsHel     Unknown  Unknown
core.cpython-39-x  00001486A98C0FB2  Unknown               Unknown  Unknown
core.cpython-39-x  00001486A98C102B  Unknown               Unknown  Unknown
core.cpython-39-x  00001486A951984F  Unknown               Unknown  Unknown
python3.9          0000556C0C6ABBF4  Unknown               Unknown  Unknown
python3.9          0000556C0C6A5E1F  _PyObject_MakeTpC     Unknown  Unknown
python3.9          0000556C0C63EF3F  Unknown               Unknown  Unknown
python3.9          0000556C0C663731  Unknown               Unknown  Unknown
python3.9          0000556C0C6EC373  _PyFunction_Vecto     Unknown  Unknown
python3.9          0000556C0C663731  Unknown               Unknown  Unknown
python3.9          0000556C0C6EB5E2  Unknown               Unknown  Unknown
python3.9          0000556C0C6EC147  _PyFunction_Vecto     Unknown  Unknown
python3.9          0000556C0C6A5657  _PyObject_Call        Unknown  Unknown
python3.9          0000556C0C7332A2  _PyEval_EvalFrame     Unknown  Unknown
python3.9          0000556C0C6EB5E2  Unknown               Unknown  Unknown
python3.9          0000556C0C6EC147  _PyFunction_Vecto     Unknown  Unknown
python3.9          0000556C0C6A5657  _PyObject_Call        Unknown  Unknown
python3.9          0000556C0C7332A2  _PyEval_EvalFrame     Unknown  Unknown
python3.9          0000556C0C6EB5E2  Unknown               Unknown  Unknown
python3.9          0000556C0C6EC147  _PyFunction_Vecto     Unknown  Unknown
python3.9          0000556C0C6A5657  _PyObject_Call        Unknown  Unknown
python3.9          0000556C0C7332A2  _PyEval_EvalFrame     Unknown  Unknown
python3.9          0000556C0C6EB7DB  Unknown               Unknown  Unknown
python3.9          0000556C0C6EC147  _PyFunction_Vecto     Unknown  Unknown
python3.9          0000556C0C6A5657  _PyObject_Call        Unknown  Unknown
python3.9          0000556C0C7332A2  _PyEval_EvalFrame     Unknown  Unknown
python3.9          0000556C0C6EB5E2  Unknown               Unknown  Unknown
python3.9          0000556C0C6EC147  _PyFunction_Vecto     Unknown  Unknown
python3.9          0000556C0C663A63  Unknown               Unknown  Unknown
python3.9          0000556C0C6EB5E2  Unknown               Unknown  Unknown
python3.9          0000556C0C79AFBC  PyEval_EvalCodeEx     Unknown  Unknown
python3.9          0000556C0C6EC60B  PyEval_EvalCode       Unknown  Unknown
python3.9          0000556C0C79B06B  Unknown               Unknown  Unknown
python3.9          0000556C0C7D15F5  Unknown               Unknown  Unknown
python3.9          0000556C0C7D6807  PyRun_StringFlags     Unknown  Unknown
python3.9          0000556C0C7D7232  Unknown               Unknown  Unknown
python3.9          0000556C0C6CA791  Unknown               Unknown  Unknown
python3.9          0000556C0C66468F  Unknown               Unknown  Unknown
python3.9          0000556C0C6EB5E2  Unknown               Unknown  Unknown
python3.9          0000556C0C79AFBC  PyEval_EvalCodeEx     Unknown  Unknown
python3.9          0000556C0C6EC60B  PyEval_EvalCode       Unknown  Unknown
python3.9          0000556C0C79B06B  Unknown               Unknown  Unknown
python3.9          0000556C0C7D15F5  Unknown               Unknown  Unknown
python3.9          0000556C0C677B45  Unknown               Unknown  Unknown
python3.9          0000556C0C7D653F  PyRun_SimpleFileE     Unknown  Unknown
python3.9          0000556C0C7D6B5D  Py_RunMain            Unknown  Unknown
python3.9          0000556C0C7D6E29  Py_BytesMain          Unknown  Unknown
libc-2.28.so       00001486B83CD493  __libc_start_main     Unknown  Unknown
python3.9          0000556C0C758D44  Unknown               Unknown  Unknown
Cgroup mem limit exceeded: 